<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TITUILO NUEVO</title>
</head>
<body>
    <div class="nav">
        <div class="navbar">
            <ul>
                <li>servicio 1</li>
                <li><a href="dashboard.phtml"></a></li>
            </ul>
        </div>
    </div>
    <input type="button" value="agregar filas" onClick="agregar()">
    <div id="glosa_0">    
        <input type="text" value="" placeholder="nombre">
        <select name="" id=""s>
            <option value="">Seleccione</option>
            <option value="1">opcion 1</option>
            <option value="1">opcion 2</option>
            <option value="1">opcion 3</option>
            <option value="1">opcion 4</option>
        </select>
    </div>
</body>
<script>
    function agregar(){
        //alert("agregando");
        console.log(length(document.getElementById('glosa_0').value));
       var glosa = document.getElementById('glosa_0').value="ahora tiene este valor";
       console.log(glosa);
    }
</script>

</html>