<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <input type="button" value="agregar filas" onClick="agregar()">
    <div id="glosa_0">    
        <input type="text" value="" placeholder="nombre">
        <select name="" id=""s>
            <option value="">Seleccione</option>
            <option value="1">opcion 1</option>
        </select>
    </div>
</body>
<script>
    function agregar(){
        //alert("agregando");
        console.log(length(document.getElementById('glosa_0').value));
       var glosa = document.getElementById('glosa_0').value="ahora tiene este valor";
       console.log(glosa);
    }
</script>

</html>